name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-integrity:
    runs-on: ubuntu-latest
    steps:
      - name: âš™ï¸ Git Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: âš™ï¸ Install Node versions
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 18

      - name: âš™ï¸ Install dependencies
        run: npm ci

      - name: ğŸ‘€ Lint
        run: npm run lint

      - name: ğŸ‘€ Format
        run: npm run lint

      - name: ğŸ“¦ Build Docs
        run: npm run build

      - name: ğŸ“¦ Build container image
        run: docker build .
